name: Deploy to IONOS (main only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (prod)
        run: npm run build -- --configuration production --base-href /browser/

      - name: Show build output (debug)
        run: |
          echo "APP_DIST=${{ secrets.APP_DIST }}"
          ls -la "${{ secrets.APP_DIST }}" || true
          find "${{ secrets.APP_DIST }}" -maxdepth 2 -type f -name "index.html" -print || true

      - name: Install lftp
        run: sudo apt-get update -y && sudo apt-get install -y lftp

      - name: Deploy to IONOS via SFTP mirror (delete remote)
        env:
          HOST:        ${{ secrets.HOST }}
          USERNAME:    ${{ secrets.USERNAME }}
          PASSWORD:    ${{ secrets.PASSWORD }}
          LOCAL_DIR:   ${{ secrets.APP_DIST }}
          REMOTE_DIR:  ${{ secrets.REMOTE_DIR }}
        run: |
          echo "LOCAL_DIR=$LOCAL_DIR"
          echo "REMOTE_DIR=$REMOTE_DIR"
          test -d "$LOCAL_DIR" || (echo "x $LOCAL_DIR introuvable" && exit 1)

          lftp -u "$USERNAME","$PASSWORD" sftp://$HOST << EOF
          set sftp:auto-confirm yes
          set net:max-retries 2
          set net:timeout 30
          set xfer:log 1
          mirror -R --delete --verbose --parallel=4 "$LOCAL_DIR" "$REMOTE_DIR"
          bye
          EOF


      - name: List remote dir (debug)
        env:
          HOST:       ${{ secrets.HOST }}
          USERNAME:   ${{ secrets.USERNAME }}
          PASSWORD:   ${{ secrets.PASSWORD }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          lftp -u "$USERNAME","$PASSWORD" sftp://$HOST << 'EOF'
          set sftp:auto-confirm yes
          ls -la "$REMOTE_DIR"
          bye
          EOF
